### ISSUE TITLE
Create page structure

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#1]
## Summary
Use flutter default project to build upon and develop personal app structure with many pages.

## Tasks
- [x] Create multiple pages
- [x] Use navigation to move between pages
- [x] Add buttons to move between pages

**Comment by joshtowell** [comment]
## New extended tasks
- [x] Add light and dark theme structure
- [x] Add responsive builder structure
- [x] Add page routing structure
