### ISSUE TITLE
Move education and others to objects

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#11]
## Summary
Move education, etc. instances to individual objects - like work and project items.

## Tasks
- [ ] Add education object
- [ ] Add education data to JSON
- [ ] Add qualification object
- [ ] Add qualification data to JSON

## Resources
_Add any resources from external sites_

## Additional notes
_Add any additional notes relevant to participants_
