### ISSUE TITLE
Look into Firebase for remote content setting

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#12]
## Summary
Look into Firebase for remote content setting and updating information in the web app.

## Tasks
- [ ] Research for best option (Firebase?)
- [ ] Implement into web app
- [ ] Test using new values

## Resources
_Add any resources from external sites_

## Additional notes
_Add any additional notes relevant to participants_
