### ISSUE TITLE
Add barebones UI to landing page

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#3]
## Summary
Create UI text themes and landing page structure ready for content to be entered.

## Tasks
- [x] Define UI text themes
- [x] Create sections for landing page
- [x] Fill sections with basic content
- [x] Make issues for developing each section

### Text theme inspiration:
- [Motiv website](https://www.advictorem.agency/case-studies/motiv-ring)
### Font styles inspiration:
- [Interactive designer website](http://geneross.co/index.php)

## Additional notes
_Add any additional notes relevant to participants_

**Comment by joshtowell** [comment]
## Extra Tasks
- [x] Adjust colours for UI hierarchy in light and dark modes (tips in _constants.dart_)
