### ISSUE TITLE
Create bio content

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#5]
## Summary
Write and format an attractive yet concise biography.

## Tasks
- [x] Write summary line
- [ ] Write goals/aims/deliverables
- [ ] Write fun and informative short paragraph
- [x] Choose format that looks best

## Resources
[One-liner](http://geneross.co/index.php)
[Short para bio](https://www.quintinlodge.com/)
[Short para bio](https://davidhellmann.com/)
[Longer bio](https://www.anthonydesigner.com/about/)
[Longer bio](http://www.themustafacelik.com/about/)

## Additional notes
_Add any additional notes relevant to participants_

**Comment by joshtowell** [comment]
Taken abridged design
