### ISSUE TITLE
Create qualifications content

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#6]
## Summary
Create a list of qualifications of merit and display them attractively.

## Tasks
- [x] Create list of sub-grouped qualifications to show
- [x] Choose format to display in
- [x] Decide interactive method

## Resources
[Simple grouped list](https://www.quintinlodge.com/)
[Select dropdown images](https://pmichal.me/index.html)
[List with descriptors](https://zhenyary.com/about)

## Additional notes
_Add any additional notes relevant to participants_

**Comment by joshtowell** [comment]
Completed
