### ISSUE TITLE
Create experience content

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#7]
## Summary
Create a clear and logical timeline of experiences and descriptions without length.

## Tasks
- [x] Decide experiences to show and what descriptions to use
- [ ] Create a UI layout for the timeline
- [x] Add content to timeline
- [x] Decide on interaction for user

## Resources
[Clean list](https://davidhellmann.com/about)

## Additional notes
_Add any additional notes relevant to participants_

**Comment by joshtowell** [comment]
Style/approach now different
