### ISSUE TITLE
Create contact content

### ISSUE THREAD

**Issue by joshtowell** [joshtowell/flutter-portfolio#9]
## Summary
Create an appealing and direct Contact Me section to allow users to easily reach out to me or learn more.

## Tasks
- [ ] Create one-sentence to attract and inform user
- [ ] Add graphic to engage
- [ ] Add social links with interactive UI

## Resources
[Colour text](https://www.anthonydesigner.com/about/)
[Clean UI](https://www.themustafacelik.com/)
[Obvious icons](https://davidhellmann.com/)
[Icon and link](https://wearewiser.com/academy)

## Additional notes
_Add any additional notes relevant to participants_

**Comment by joshtowell** [comment]
Not yet implemented
